---
- name: install and configure httpd
  hosts: nodes
  become: yes
  tasks:
    - name: install httpd & firewalld
      yum:
        name:
          - httpd
          - firewalld
        state: latest
    - name: start httpd
      service:
        name: httpd
        enabled: true
        state: started
    - name: start firewall
      service:
        name: firewalld
        enabled: true
        state: started
    - name: open firewall port
      firewalld:
        service: http
        permanent: true
        state: enabled
        immediate: yes
    - name: copy html content
      copy:
        content: "Welcome to our website"
        dest: /var/www/html/index.html
- name: ping local host
  hosts: localhost
  tasks:
    - name: check who is logged in
      shell:
        command: "whoami"
